;;;; -- Prompt rendering --
;;;
;;; The prompt is generated by starship when available, with a plain
;;; colored fallback otherwise. Starship receives the last exit status,
;;; the duration of the last command and the terminal width.

(in-package #:cclsh)

(defun prompt-starship (status duration-milliseconds columns)
  "Ask starship to render a prompt. Returns the prompt string or NIL
   when starship is unavailable or fails."
  (handler-case
      (let* ((output    (make-string-output-stream))
             (arguments (list "prompt"
                              (format nil "--status=~d" status)
                              (format nil "--cmd-duration=~d" duration-milliseconds)
                              (format nil "--terminal-width=~d" columns)
                              (format nil "--jobs=~d" (jobs-count))))
             (process   (run-program "starship" arguments
                                     :input  nil
                                     :output output
                                     :error  nil
                                     :wait   t
                                     :external-format ':utf-8)))
        (multiple-value-bind (state code)
            (external-process-status process)
          (let ((prompt (get-output-stream-string output)))
            (if (and (eq state ':exited) (zerop code) (plusp (length prompt)))
                prompt
                nil))))
    (error () nil)))

(defun prompt-fallback ()
  "Render a simple colored prompt used when starship is missing."
  (let* ((directory (string-right-trim "/" (namestring (current-directory))))
         (home      (home-directory))
         (shortened (cond ((string= directory home)
                           "~")
                          ((and (> (length directory) (length home))
                                (string= home (subseq directory 0 (length home)))
                                (char= (char directory (length home)) #\/))
                           (concatenate 'string "~" (subseq directory (length home))))
                          ((string= directory "")
                           "/")
                          (t
                           directory))))
    (format nil "~a ~a "
            (ansi-colorize shortened ':green :bold t)
            (ansi-colorize "$" (if (zerop *last-status*) ':white ':red)))))

(defun prompt-render (status duration-milliseconds columns)
  "Return the prompt string for the next command line."
  (or (prompt-starship status duration-milliseconds columns)
      (prompt-fallback)))
